### ISSUE TITLE
Add shortcode for Tumblr post embeds

### ISSUE THREAD

**Issue by goldenapples** [wp-shortcake/shortcake-bakery#159] opened 2015-11-23 14:32 UTC
Example of embed code that needs to be reversed:

```
<div class="tumblr-post" data-href="https://embed.tumblr.com/embed/post/UuVb8hOzuSx2t9jZINxiZg/133755258901" data-did="104cad8eb4ebebb9af3adee9174d0557bd7db248"><a href="http://wholeearthradar.tumblr.com/post/133755258901/sunday-november-22-2015-brazil-australia-south">http://wholeearthradar.tumblr.com/post/133755258901/sunday-november-22-2015-brazil-australia-south</a></div><script async src="https://secure.assets.tumblr.com/post.js"></script>
```

**Comment by danielbachhuber** [comment] 2015-11-23 14:43
Duplicate of #29

**Closed by danielbachhuber** 2015-11-23 14:43 UTC
